title: Mark Chapman Memorial
cardContent:  |
  Perhaps 
  they are not the stars,
  but rather openings
  in Heaven
  where the love
  of our lost ones
  shines down
  to let us know
  they are with us.
